all: base
base:
	g++ -O3 -std=c++11 -o ../compiled/eclat_lamp_cmh_2k_bool eclat_lamp_cmh_2k.cpp
	g++ -O3 -std=c++11 -o ../compiled/eclat_lamp_cmh_Mk_bool eclat_lamp_cmh_Mk.cpp
	g++ -O3 -std=c++11 -o ../compiled/eclat_bonf_cmh_bool eclat_bonf_cmh.cpp
	g++ -O3 -std=c++11 -o ../compiled/eclat_lamp_cmh_np_bool eclat_lamp_cmh_np.cpp
